#
# Super simple example of a Dockerfile
#
FROM debian:buster

WORKDIR /home/rem_build

RUN apt-get update -y
RUN apt-get install -y build-essential rake gcc-arm-none-eabi gcc-avr avr-libc git subversion unzip wget curl make python sdcc sdcc-libraries cppcheck

RUN git clone https://github.com/franzflasch/REM.git

RUN /bin/bash -c "/home/rem_build/REM/tests/run_all_rem_tests.sh /home/rem_build/REM"
