#
# Super simple example of a Dockerfile
#
FROM ubuntu:trusty

WORKDIR /home/rem_build

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y
RUN apt-get install -y rake gcc-arm-none-eabi gcc-avr avr-libc git subversion unzip wget make python

RUN git clone https://github.com/franzflasch/REM.git

RUN /bin/bash -c "/home/rem_build/REM/tests/run_all_rem_tests.sh /home/rem_build/REM"
