#
# Super simple example of a Dockerfile
#
FROM debian:jessie

WORKDIR /home/rem_build

RUN apt-get update -y
RUN apt-get install -y rake gcc-arm-none-eabi gcc-avr avr-libc git subversion unzip wget make python

RUN git clone https://github.com/franzflasch/REM.git

RUN ./home/rem_build/REM/tests/run_all_rem_tests.sh /home/rem_build/REM
