#!/usr/bin/env ruby
begin
  require 'rem_path'
rescue LoadError
  puts "rem_path.rb was not found. REM is probably not installed as a gem package. Trying relative path."
  require_relative '../lib/rem_path'
end

args_string = ARGV.join(" ")
rem_path=get_rem_path()
rem_rake_file="#{rem_path}/rem_core.rb"

exec("rake -f #{rem_rake_file} #{args_string}")
