#!/bin/bash

# Get directory of the REM build scripts
REM_RAKEFILE_DIR="$(dirname "$(readlink -f "$0")")"

# Now start the rake command with all given parameters
rake -f $REM_RAKEFILE_DIR/Rakefile "$@"
